In [12]:
from params.position_params import Position_parameters
import json
import numpy as np

In [6]:
dp = Position_parameters(x_pixels=63, y_pixels=139)

In [11]:
dp.y_coordinates.shape

(139, 63)

In [39]:
np.repeat(dp.x_coordinates[:,:,np.newaxis],axis=2,repeats=2).reshape(139,-1).shape

(139, 126)

In [32]:
dp.x_coordinates[0]

array([0.        , 0.0483871 , 0.09677419, 0.14516129, 0.19354839,
       0.24193548, 0.29032258, 0.33870968, 0.38709677, 0.43548387,
       0.48387097, 0.53225806, 0.58064516, 0.62903226, 0.67741935,
       0.72580645, 0.77419355, 0.82258065, 0.87096774, 0.91935484,
       0.96774194, 1.01612903, 1.06451613, 1.11290323, 1.16129032,
       1.20967742, 1.25806452, 1.30645161, 1.35483871, 1.40322581,
       1.4516129 , 1.5       , 1.5483871 , 1.59677419, 1.64516129,
       1.69354839, 1.74193548, 1.79032258, 1.83870968, 1.88709677,
       1.93548387, 1.98387097, 2.03225806, 2.08064516, 2.12903226,
       2.17741935, 2.22580645, 2.27419355, 2.32258065, 2.37096774,
       2.41935484, 2.46774194, 2.51612903, 2.56451613, 2.61290323,
       2.66129032, 2.70967742, 2.75806452, 2.80645161, 2.85483871,
       2.90322581, 2.9516129 , 3.        ])

In [42]:
np.ravel(np.column_stack((
    np.ones(10),
    np.zeros(10)
    )))

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0.])

In [44]:
(np.arange(240).reshape(4,-1))

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
        159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
        172, 173, 174, 175

In [48]:
np.mean((np.arange(240).reshape(4,-1))[:,:,np.newaxis].reshape(4,-1,2), axis=2)[0]

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5, 12.5, 14.5, 16.5, 18.5, 20.5,
       22.5, 24.5, 26.5, 28.5, 30.5, 32.5, 34.5, 36.5, 38.5, 40.5, 42.5,
       44.5, 46.5, 48.5, 50.5, 52.5, 54.5, 56.5, 58.5])