In [1]:
from params.position_params import Position_parameters
from params.scan_params import Scan_parameters
from daq_driver import reset_daq, set_z_height, read_daq_output
import json
import numpy as np

In [2]:
scan_parameters = Scan_parameters()
reset_daq(scan_parameters)

array([-2.36926461e-04, -5.65699424e-04, -2.36926461e-04,  9.18465016e-05])

In [3]:
read_daq_output(scan_parameters)

array([ 9.18465016e-05, -2.36926461e-04, -2.36926461e-04, -2.36926461e-04])

In [18]:
position_parameters = Position_parameters(
                                            x_size=15,
                                            y_size=15,
                                            x_pixels=256,
                                            y_pixels=150,
                                            z_center=19)
set_z_height(scan_parameters, position_parameters)

In [5]:
read_daq_output(scan_parameters)

array([-2.36926461e-04, -2.36926461e-04, -2.36926461e-04,  9.18465016e-05])