In [33]:
from params.position_params import Position_parameters
from params.scan_params import Scan_parameters
from daq_driver import reset_daq, set_z_height, read_daq_output
import json
import numpy as np

In [35]:
scan_parameters = Scan_parameters()
reset_daq(scan_parameters)

array([ 9.18465016e-05, -5.65699424e-04, -5.65699424e-04,  9.18465016e-05])

In [34]:
read_daq_output(scan_parameters)

array([-2.36926461e-04, -2.36926461e-04, -2.36926461e-04,  9.18465016e-05])

In [38]:
position_parameters = Position_parameters(
                                            x_size=10,
                                            y_size=10,
                                            # x_center=0,
                                            # y_center=0,
                                            x_pixels=128,
                                            y_pixels=100,
                                            z_center=20)
set_z_height(scan_parameters, position_parameters)

In [4]:
position_parameters.y_output

array([[4.25      , 4.25      , 4.25      , ..., 4.25      , 4.25      ,
        4.25      ],
       [4.25      , 4.25      , 4.25      , ..., 4.25      , 4.25      ,
        4.25      ],
       [4.26515152, 4.26515152, 4.26515152, ..., 4.26515152, 4.26515152,
        4.26515152],
       ...,
       [5.73484848, 5.73484848, 5.73484848, ..., 5.73484848, 5.73484848,
        5.73484848],
       [5.75      , 5.75      , 5.75      , ..., 5.75      , 5.75      ,
        5.75      ],
       [5.75      , 5.75      , 5.75      , ..., 5.75      , 5.75      ,
        5.75      ]])

In [6]:
read_daq_output(scan_parameters)

array([4.99976480e+00, 4.99976480e+00, 5.99773924e-01, 9.18465016e-05])